"""data migration: normalize subsidy model_name values

This autogenerated migration contains the mapping pairs used to update
`subsidies.model_name`. It performs UPDATEs in-place. Review before applying
and set an appropriate `down_revision` if you use alembic history.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '20251031_subsidy_data_migration'
down_revision = None
branch_labels = None
depends_on = None

MAPPINGS = [
    ("더 뉴 아이오닉6 2wd 롱레인지 18인치", "더 뉴 아이오닉6 롱레인지 2WD 18인치"),
    ("더 뉴 아이오닉6 2wd 스탠다드 18인치", "더 뉴 아이오닉6 스탠다드 2WD 18인치"),
    ("더 뉴 아이오닉6 2wd 롱레인지 20인치", "더 뉴 아이오닉6 롱레인지 2WD 20인치"),
    ("더 뉴 아이오닉6 2wd 롱레인지 n라인 20인치", "더 뉴 아이오닉6 롱레인지 N라인 2WD 20인치"),
    ("더 뉴 아이오닉6 awd 롱레인지 18인치", "더 뉴 아이오닉6 롱레인지 AWD 18인치"),
    ("더 뉴 아이오닉6 awd 롱레인지 20인치", "더 뉴 아이오닉6 롱레인지 AWD 20인치"),
    ("더 뉴 아이오닉6 awd 롱레인지 n라인 20인치", "더 뉴 아이오닉6 롱레인지 N라인 AWD 20인치"),

    ("코나 일렉트릭 2WD 롱레인지 17인치", "코나 일렉트릭 롱레인지 2WD 17인치"),
    ("코나 일렉트릭 2WD 스탠다드 17인치", "코나 일렉트릭 스탠다드 2WD 17인치"),
    ("코나 일렉트릭 2WD 롱레인지 17인치(빌트인 캠)", "코나 일렉트릭 롱레인지 2WD 17인치(빌트인 캠)"),
    ("코나 일렉트릭 2WD 롱레인지 19인치(빌트인 캠)", "코나 일렉트릭 롱레인지 2WD 19인치(빌트인 캠)"),

    ("더뉴아이오닉5 2WD 롱레인지 19인치", "더 뉴 아이오닉5 롱레인지 2WD 19인치"),
    ("더뉴아이오닉5 2WD 스탠다드 19인치", "더 뉴 아이오닉5 스탠다드 2WD 19인치"),
    ("더뉴아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용", "더 뉴 아이오닉5 롱레인지 2WD 19인치(빌트인 캠 미적용)"),
    ("더뉴아이오닉5 2WD 롱레인지 20인치", "더 뉴 아이오닉5 롱레인지 2WD 20인치"),
    ("더뉴아이오닉5 2WD 롱레인지 N라인 20인치", "더 뉴 아이오닉5 N라인 롱레인지 2WD 20인치"),
    ("더뉴아이오닉5 AWD 롱레인지 19인치", "더 뉴 아이오닉5 롱레인지 AWD 19인치"),
    ("더뉴아이오닉5 AWD 롱레인지 20인치", "더 뉴 아이오닉5 롱레인지 AWD 20인치"),
    ("더뉴아이오닉5 AWD 롱레인지 N라인 20인치", "더 뉴 아이오닉5 롱레인지 N라인 AWD 20인치"),
    ("아이오닉5 N", "아이오닉5 N라인"),

    ("더뉴EV6 스탠다드", "더 뉴 EV6 스탠다드"),
    ("더뉴EV6 롱레인지 2WD 19인치", "더 뉴 EV6 롱레인지 2WD 19인치"),
    ("더뉴EV6 롱레인지 2WD 20인치", "더 뉴 EV6 롱레인지 2WD 20인치"),
    ("더뉴EV6 롱레인지 4WD 19인치", "더 뉴 EV6 롱레인지 4WD 19인치"),
    ("더뉴EV6 롱레인지 4WD 20인치", "더 뉴 EV6 롱레인지 4WD 20인치"),
    ("더뉴EV6 GT", "더 뉴 EV6 GT"),

    ("scenic", "SCENIC"),

    ("Polestar 4 Long Range Dual Motor 20인치", "Polestar 4 롱레인지 Dual Motor 20인치"),
    ("Polestar 4 Long Range Dual Motor 22인치 performance", "Polestar 4 롱레인지 Dual Motor 22인치 performance"),
    ("Polestar 4 Long Range Single Motor 20인치", "Polestar 4 롱레인지 Single Motor 20인치"),

    ("볼보 EX 30cc Twin", "볼보 EX30 Ultra"),
    ("볼보 EX30 Single Motor ER", "볼보 EX30 Core"),

    ("BYD SEAL Dynamic awd", "BYD SEAL Dynamic AWD"),
]


def upgrade() -> None:
    conn = op.get_bind()
    for old, new in MAPPINGS:
        # use parameterized execution to avoid SQL injection and quoting issues
        conn.execute(text("""UPDATE subsidies SET model_name = :new WHERE model_name = :old"""), {"new": new, "old": old})


def downgrade() -> None:
    conn = op.get_bind()
    # reverse mappings in reverse order
    for old, new in reversed(MAPPINGS):
        conn.execute(text("""UPDATE subsidies SET model_name = :old WHERE model_name = :new"""), {"new": new, "old": old})
